"""Recreate attendance schema

Revision ID: aec0b01704c7
Revises: 
Create Date: 2025-06-24 13:43:02.812487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec0b01704c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_log_id'), table_name='attendance_log')
    op.drop_table('attendance_log')
    op.add_column('attendance', sa.Column('lesson_number', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'date')
    op.drop_column('attendance', 'lesson_number')
    op.create_table('attendance_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_log_id'), 'attendance_log', ['id'], unique=False)
    # ### end Alembic commands ### 